---
- name: install c1-static
  hosts: c1-static
  become: yes
  become_user: root
  tasks:
    - name: yum install httpd in container
      yum:
       name: httpd
       state: latest

- name: intall c2-php
  hosts: c2-php
  become: yes
  tasks:
    - name: yum install nano
      yum:
        name: httpd
        state: latest
    - name: yum install php
      yum:
        name: php
        state: latest