# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "generic/centos8_new01"

  config.vm.provider "virtualbox" do |vb|
    # vb.name = "demogitdebianten.vagrant.vm"
    # Customize the amount of memory on the VM:
    vb.memory = "512"
    vb.cpus = 1
  end

  config.vm.hostname = "centos8"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 81, host: 8081

  config.vm.synced_folder ".", "/home/vagrant/tmp"

  config.vm.provision "shell", path: "provision.sh"
end