# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8s"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus   = 2
  end

  config.vm.define "master.puppet", primary: true do |master|
    master.vm.hostname = "master.puppet"
    master.vm.network "private_network", ip: "192.168.50.5"
    master.vm.synced_folder ".", "/vagrant"
  end

  config.vm.define "slave1.puppet" do |slave1|
      slave1.vm.hostname = "slave1.puppet"
      slave1.vm.network "private_network", ip: "192.168.50.10"
      slave1.vm.synced_folder ".", "/vagrant"
      slave1.vm.provider("virtualbox") { |vb| vb.memory = 512 }
  end

  config.vm.define "slave2.puppet" do |slave2|
    slave2.vm.hostname = "slave2.puppet"
    slave2.vm.network "private_network", ip: "192.168.50.20"
    slave2.vm.synced_folder ".", "/vagrant"
    slave2.vm.provider("virtualbox") { |vb| vb.memory = 512 }
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "puppet.yaml"
    ansible.groups   = {
      "master" => ["master.puppet"],
      "slave" => ["slave1.puppet", "slave2.puppet"],
      "slave:vars" => { "puppet_master": "192.168.50.5" }
    }
  end
end
