version: '3'

services:

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.Jenkins
    image: jenkins
    container_name: jenkins
    ports:
    - 80:8080
    networks:
    - net

networks:
  net: {}